language: python
python:
  - "3.6"
cache:
  pip: true
  directories:
    - .tox
script:
  - tox
  - coverage combine python27.coverage python35.coverage
after_success:
  - coveralls
  - codeclimate-test-reporter
