language: python
python:
  - "3.5"
cache:
  pip: true
  directories:
    - .tox
script:
  - tox
  - coverage combine python27.coverage python35.coverage
after_success:
  - coveralls
  - codeclimate-test-reporter
deploy:
  provider: pypi
  user: "${PYPI_USER_TOKEN}"
  password: "${PYPI_PW_TOKEN}"
  server: "https://testpypi.python.org"
  on:
    tags: true
