language: python
python:
  - "3.6"
addons:
  apt_packages:
    - pandoc
cache:
  pip: true
  apt: true
  directories:
    - .tox
script:
  - tox
  - coverage combine python27.coverage python35.coverage
after_success:
  - pandoc -f markdown -t rst -o README.rst README.md
  - coveralls
  - codeclimate-test-reporter
deploy:
  provider: pypi
  user:
    secure: >-
      R2R3O4H7V0aquEr74MUC264ll8I42RjZWkqLn5wFBPi71K8ABjYatEwIRSxu0iIvqyllWlP3
      3DRZHn362EDMw7byegyM+2x2Rgtdk2jgXWpIvUvasx7s/kkt6+26QmfuVLyl7IWCidFsX6D+
      PnzVjlRUSO19tAiSJiPjL7VAW3tu/VAQZLHVdJlYWLjdBesH8DLG9YFtcHdbGDwHWUNwfFH6
      EVW/SOX6SOn0dosls7sQB3nvar9fXlbL/ZhL6/Pxe5yJOYbUW8KJlx87pnmnz7rCb43kSxJ5
      vn0V3fRVAZdsgglwow0mDccatDO5g1o+b0GTZW4Yn+gZusKUg7z2QIKPyWL+CqK7X/qMzrQu
      8ggLMNdHk+XtQKkxxEH7iuwaz1qx6AKE0dIfqBzCkrcD+i9EuvVQVJ0ATJb5ZqwtYILxzEt/
      EI2phdmSApC/c7AE2hHB5qc2nptFJChK8XBoCgEL2SV+8jLyzui9yjc6A1GX4okxYnFfqBnj
      +6DIFxqXL+Ni6Jfd6EXm041jr88QbymN+HYoY7rUXDiUOaHEGwie3hqJNPr3OOvJ13hnMYmS
      pzloL11ucQvN+/NYJ+8YKXbCZ4j1nka1yRloTt5bB8SErkZIPORi5kZwNIpiTO8/aWvKci7t
      svCTGkjffq8T2zSp4AOTiLyf5KwG7ro84fc=
  password:
    secure: >-
      gRqzq4wU0ChtyTLdbWTAgk1GrEMVuyv/fF651gkDrD73zRKrk04Qbfj3mpyIc6OHPjB1NJV+
      tJo9vPuhlAqyX6JqFa51BsbKZkceYMM1fTTCCQWWSSrg8Ubwc+eJK6CBX+IofKSWreTQLcP7
      oys7BJ9Ha0rVfmB50DOFEBeBg2Iur052eMCnc9cbpzKcdpjKU5L2uTDuCjg0djAlPE6IqE0S
      UZUXqOP6NILgFqgSKPy3J45e949IzRCS1FMWEvxleKOQszKSKnKSdRLw/1sQc7U6qvuhAu3q
      aUDTbjvIB8TM0KAA8etOO+9g0PTvLC2XsQ0buOqg3KJABiBoojW2dzxbL1feq2//SG4WkDZq
      0OShJmfz1fNzKxW4DJ3+jVAH4zo2Mh+YBvOOHEB9icInMT/kgrAmD/X5RkjW5lvBm4/QKsj5
      s7VXEKWsx3pGAZMG9w/kFfk4l+UQxSloXbA//nDZDxovqZ5H4Mb/HxuHxI5jJNc/3cbfg2AN
      ljQMT7RCWF+U8J+gcAfpXvyidZiWdLt1kfIJJte8IwxWZAvzQod6P8t6cMgG57VbVLIceQSB
      P9jp/isOvHCnFjheXLCBkcmhrZnaeKAbnHFXy7gY/Ff3Ud+kgLndG58lqXZSdI/4O4V0doTf
      3b6/P+CJ0/vS4fUmi0CT81Ln5AVi7ppA+qQ=
  skip_cleanup: true
  distributions: sdist
  on:
    tags: true
